In [1]:
import numpy as np

In [2]:
a=np.array([5,6,9])

In [3]:
a=np.array([[1,2],[3,4],[4,5]])

In [4]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [5]:
a.ndim

2

In [6]:
a.itemsize


4

In [8]:
a.dtype

dtype('int32')

In [9]:
a=np.array([[1,2],[3,4],[4,5]],dtype=np.float64)

In [11]:
a.itemsize

8

In [12]:
a.size

6

In [13]:
a

array([[1., 2.],
       [3., 4.],
       [4., 5.]])

In [14]:
a.shape

(3, 2)

In [15]:
a=np.array([[1,2],[3,4],[4,5]],dtype=complex)

In [16]:
a


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
l=range(5)

In [21]:
l


range(0, 5)

In [22]:
l[0]

0

In [23]:
l[1]

1

In [24]:
np.arange(1,5)

array([1, 2, 3, 4])

In [26]:
np.arange(1,5,2)

array([1, 3])

In [27]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [29]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [30]:
a.shape

(3, 2)

In [31]:
a.reshape(2,3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 4.+0.j, 5.+0.j]])

In [32]:
a.reshape(6,1)

array([[1.+0.j],
       [2.+0.j],
       [3.+0.j],
       [4.+0.j],
       [4.+0.j],
       [5.+0.j]])

In [33]:
a.ravel()

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 4.+0.j, 5.+0.j])

In [34]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j]])

In [35]:
a=np.array([[1,2],[3,4],[4,5]])

In [40]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [36]:
a.min()

1

In [37]:
a.max()

5

In [38]:
a.sum()

19

In [39]:
a.sum(axis=0)

array([ 8, 11])

In [42]:
a.sum(axis=1)

array([3, 7, 9])

In [43]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.        , 2.23606798]])

In [45]:
np.std(a)

1.3437096247164249

In [51]:
a=np.array([[1,2],[3,4]])

In [52]:
b=np.array([[5,6],[7,8]])

In [53]:
a

array([[1, 2],
       [3, 4]])

In [54]:
b

array([[5, 6],
       [7, 8]])

In [55]:
a+b

array([[ 6,  8],
       [10, 12]])

In [56]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [57]:
a.dot(b)

array([[19, 22],
       [43, 50]])